# Generated by Django 6.0.5 on 2026-06-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsession_alter_questionhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'verbose_name': 'Chat', 'verbose_name_plural': 'Chats'},
        ),
        migrations.AlterModelOptions(
            name='questionhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Question', 'verbose_name_plural': 'Question History'},
        ),
        migrations.AlterField(
            model_name='questionhistory',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
