# Generated by Django 6.0.5 on 2026-06-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionhistory',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
