# Generated by Django 6.0.5 on 2026-06-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_private',
            field=models.BooleanField(default=True, help_text='Private = only owner can use it. Public = everyone can use it.'),
        ),
    ]
